version: '3'

services:
  mssql:
    container_name: sqlserver-dev
    build:
      context: ./docker/sqlserver/
    image: sqlserver
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password.1
      - MSSQL_PID=Developer # Express # SQL Serverのエディションまたはプロダクトキー
      - MSSQL_LCID=1042 # ロケールID 日本語 (https://www.ryadel.com/en/microsoft-windows-lcid-list-decimal-and-hex-all-locale-codes-ids/)
    #  - MSSQL_COLLATION=Japanese_CI_AS # 照合順
      - DB_NAME=sqlserver # 初回起動時のDB存在判定のために使用します。
    volumes: # docker-compose.yml ファイルのあるフォルダに mssqlserver フォルダが作成され、データが保存されます。
      - ./docker/sqlserver/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/sqlserver/data:/var/opt/mssql/data
      - ./docker/sqlserver/log:/var/opt/mssql/log
      - ./docker/sqlserver/secrets:/var/opt/mssql/sec